<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-23 at 17:12:27.
 */
class ConfigFactoryTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var ConfigFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ConfigFactory;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ConfigFactory::getConfigVar
     * @todo   Implement testGetConfigVar().
     */
    public function testGetConfigVar()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConfigFactory::parse_ini_file_advanced
     * @todo   Implement testParse_ini_file_advanced().
     */
    public function testParse_ini_file_advanced()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConfigFactory::recursive_parse
     * @todo   Implement testRecursive_parse().
     */
    public function testRecursive_parse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConfigFactory::toObject
     * @todo   Implement testToObject().
     */
    public function testToObject()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConfigFactory::checkRequest
     * @todo   Implement testCheckRequest().
     */
    public function testCheckRequest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ConfigFactory::resolveCredential
     * @todo   Implement testResolveCredential().
     */
    public function testResolveCredential()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
