<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-23 at 17:08:42.
 */
class ErrorHandlerTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var ErrorHandler
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ErrorHandler;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ErrorHandler::badRequest
     * @todo   Implement testBadRequest().
     */
    public function testBadRequest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ErrorHandler::badArguments
     * @todo   Implement testBadArguments().
     */
    public function testBadArguments()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ErrorHandler::badDomain
     * @todo   Implement testBadDomain().
     */
    public function testBadDomain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
