<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-23 at 17:08:17.
 */
class HttpClientTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var HttpClient
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new HttpClient;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers HttpClient::doRequest
     * @todo   Implement testDoRequest().
     */
    public function testDoRequest()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HttpClient::setUserAgent
     * @todo   Implement testSetUserAgent().
     */
    public function testSetUserAgent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HttpClient::setHeader
     * @todo   Implement testSetHeader().
     */
    public function testSetHeader()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HttpClient::setAuth
     * @todo   Implement testSetAuth().
     */
    public function testSetAuth()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HttpClient::setPost
     * @todo   Implement testSetPost().
     */
    public function testSetPost()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HttpClient::setUrl
     * @todo   Implement testSetUrl().
     */
    public function testSetUrl()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HttpClient::getCurlInfo
     * @todo   Implement testGetCurlInfo().
     */
    public function testGetCurlInfo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
